name: pipeline-deploy-s3
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get install pandoc
    - run: pandoc README.md -f markdown -t html -s -o index.html
    - run: ls -la
    - uses: actions/upload-artifact@v4
      with:
        name: site
        path: index.html
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - run: npm --prefix backend install
    - run: npm --prefix backend test -- --testPathIgnorePatterns=backend/src/products/products.service.spec.ts
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_EC2_METADATA_DISABLED: true
      BUCKET_S3: ${{ vars.BUCKET_S3 }}
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: site
        path: index.html
    - run: ls -la
    - run: aws s3 cp index.html s3://$BUCKET_S3 --recursive
