name: provisioning ecr-eb

on:
  workflow_dispatch:


jobs:
  provisioning:
    runs-on: ubuntu-latest
    env:
      # Credenciais AWS
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

      # Variáveis TF_VAR para Terraform
      TF_VAR_AWS_REGION: ${{ vars.AWS_REGION }}
      TF_VAR_PROJECT_NAME: ${{ vars.PROJECT_NAME }}
      TF_VAR_MODULE_NAME: ${{ vars.MODULE_NAME }}
      TF_VAR_S3_BUCKET: ${{ vars.S3_BUCKET }}
      TF_VAR_SOLUTION_STACK_NAME: ${{ vars.SOLUTION_STACK_NAME }}
      TF_VAR_EnvironmentType: ${{ vars.ENVIRONMENT_TYPE }}
      TF_VAR_LoadBalancerType: ${{ vars.LOAD_BALANCER_TYPE }}
      TF_VAR_MinSize: ${{ vars.MIN_SIZE }}
      TF_VAR_MaxSize: ${{ vars.MAX_SIZE }}
      TF_VAR_DeploymentPolicy: ${{ vars.DEPLOYMENT_POLICY }}
      TF_VAR_BatchSizeType: ${{ vars.BATCH_SIZE_TYPE }}
      TF_VAR_BatchSize: ${{ vars.BATCH_SIZE }}
      TF_VAR_Timeout: ${{ vars.TIMEOUT }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: |
        terraform -chdir=.environment init \
          -backend-config="bucket=${{ vars.S3_BUCKET }}" \
          -backend-config="key=state/terraform.tfstate" \
          -backend-config="region=${{ vars.AWS_REGION }}" \
          -backend-config="encrypt=true"

    - name: Terraform Format
      run: terraform -chdir=.environment fmt -check

    - name: Terraform Validate
      run: terraform -chdir=.environment validate

    - name: Terraform Plan
      run: terraform -chdir=.environment plan -input=false -out=tfplan

    - name: Terraform Apply
      run: terraform -chdir=.environment apply -auto-approve tfplan
